export type TeamAsset = {
  id: string;
  label: string;
  shortLabel: string;
  primary: string;
  secondary: string;
  accent: string;
  badgeAssetPath: string | null;
  badgePlate?: "default" | "light";
  carImagePath: string | null;
  carImageAlt: string;
  fallbackImagePath: string;
  imageFit?: "cover" | "contain";
  imagePosition?: string;
};

export type CircuitAsset = {
  id: string;
  countryCode: string;
  region: string;
  layoutAssetPath: string | null;
  layoutSourceLabel: string | null;
  layoutSourceUrl: string | null;
  geoJsonFeatureId: string | null;
  lapRecordTime: string | null;
  lapRecordDriver: string | null;
  lapRecordYear: number | null;
};

const sharedTeamFallback = "/assets/teams/car-placeholder.svg";

const fallbackTeam: TeamAsset = {
  id: "default",
  label: "Constructor",
  shortLabel: "TEAM",
  primary: "#636b78",
  secondary: "#9da6b2",
  accent: "#e10600",
  badgeAssetPath: null,
  carImagePath: null,
  carImageAlt: "Formula 1 constructor media placeholder",
  fallbackImagePath: sharedTeamFallback,
};

const fallbackCircuit: CircuitAsset = {
  id: "default",
  countryCode: "--",
  region: "Circuit",
  layoutAssetPath: null,
  layoutSourceLabel: null,
  layoutSourceUrl: null,
  geoJsonFeatureId: null,
  lapRecordTime: null,
  lapRecordDriver: null,
  lapRecordYear: null,
};

export const CURRENT_2026_TEAM_IDS = [
  "mercedes",
  "ferrari",
  "mclaren",
  "haas",
  "red_bull",
  "racing_bulls",
  "alpine",
  "audi",
  "williams",
  "cadillac",
  "aston_martin",
] as const;

const teamAliases: Record<string, string> = {
  rb: "racing_bulls",
  alphatauri: "racing_bulls",
  haas_f1_team: "haas",
};

const teamAssetMap: Record<string, TeamAsset> = {
  mercedes: {
    id: "mercedes",
    label: "Mercedes",
    shortLabel: "MER",
    primary: "#00d2be",
    secondary: "#7ef5e7",
    accent: "#d9dde3",
    badgeAssetPath: "/assets/teams/logos/mercedes.svg",
    carImagePath: "/assets/teams/2026/mercedes.webp",
    carImageAlt: "Mercedes AMG Petronas 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 58%",
  },
  ferrari: {
    id: "ferrari",
    label: "Ferrari",
    shortLabel: "FER",
    primary: "#dc0000",
    secondary: "#ffda59",
    accent: "#ffffff",
    badgeAssetPath: "/assets/teams/logos/ferrari.svg",
    carImagePath: "/assets/teams/2026/ferrari.webp",
    carImageAlt: "Scuderia Ferrari 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 48%",
  },
  mclaren: {
    id: "mclaren",
    label: "McLaren",
    shortLabel: "MCL",
    primary: "#ff8700",
    secondary: "#89f0ff",
    accent: "#ffffff",
    badgeAssetPath: "/assets/teams/logos/mclaren.svg",
    badgePlate: "light",
    carImagePath: "/assets/teams/2026/mclaren.webp",
    carImageAlt: "McLaren 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 54%",
  },
  haas: {
    id: "haas",
    label: "Haas F1 Team",
    shortLabel: "HAA",
    primary: "#8f97a3",
    secondary: "#ff3b30",
    accent: "#ffffff",
    badgeAssetPath: "/assets/teams/logos/haas.svg",
    carImagePath: "/assets/teams/2026/haas.webp",
    carImageAlt: "Haas F1 Team 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 48%",
  },
  red_bull: {
    id: "red_bull",
    label: "Red Bull Racing",
    shortLabel: "RBR",
    primary: "#1e41ff",
    secondary: "#f5c542",
    accent: "#dc143c",
    badgeAssetPath: "/assets/teams/logos/red-bull.svg",
    carImagePath: "/assets/teams/2026/red-bull.webp",
    carImageAlt: "Oracle Red Bull Racing 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 52%",
  },
  racing_bulls: {
    id: "racing_bulls",
    label: "Racing Bulls",
    shortLabel: "RB",
    primary: "#4d63ff",
    secondary: "#d7dce4",
    accent: "#ffffff",
    badgeAssetPath: null,
    carImagePath: "/assets/teams/2026/racing-bulls.webp",
    carImageAlt: "Racing Bulls 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 52%",
  },
  alpine: {
    id: "alpine",
    label: "Alpine",
    shortLabel: "ALP",
    primary: "#0090ff",
    secondary: "#ff4db8",
    accent: "#dfe6ee",
    badgeAssetPath: null,
    carImagePath: "/assets/teams/2026/alpine.webp",
    carImageAlt: "BWT Alpine 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 52%",
  },
  audi: {
    id: "audi",
    label: "Audi",
    shortLabel: "AUD",
    primary: "#d10000",
    secondary: "#eceff4",
    accent: "#ffffff",
    badgeAssetPath: "/assets/teams/logos/audi.svg",
    badgePlate: "light",
    carImagePath: "/assets/teams/2026/audi.webp",
    carImageAlt: "Audi 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 54%",
  },
  williams: {
    id: "williams",
    label: "Williams",
    shortLabel: "WIL",
    primary: "#005aff",
    secondary: "#8fbeff",
    accent: "#ffffff",
    badgeAssetPath: "/assets/teams/logos/williams.svg",
    badgePlate: "light",
    carImagePath: "/assets/teams/2026/williams.webp",
    carImageAlt: "Williams Racing 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 46%",
  },
  cadillac: {
    id: "cadillac",
    label: "Cadillac",
    shortLabel: "CAD",
    primary: "#f5f7fb",
    secondary: "#131922",
    accent: "#8cb4ff",
    badgeAssetPath: "/assets/teams/logos/cadillac.svg",
    badgePlate: "light",
    carImagePath: "/assets/teams/2026/cadillac.webp",
    carImageAlt: "Cadillac 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 58%",
  },
  aston_martin: {
    id: "aston_martin",
    label: "Aston Martin",
    shortLabel: "AMR",
    primary: "#006f62",
    secondary: "#7ad7c8",
    accent: "#ced4db",
    badgeAssetPath: "/assets/teams/logos/aston-martin.svg",
    badgePlate: "light",
    carImagePath: "/assets/teams/2026/aston-martin.webp",
    carImageAlt: "Aston Martin Aramco 2026 Formula 1 car",
    fallbackImagePath: sharedTeamFallback,
    imagePosition: "center 48%",
  },
  sauber: {
    id: "sauber",
    label: "Sauber",
    shortLabel: "SAU",
    primary: "#52e252",
    secondary: "#d8ff8c",
    accent: "#101410",
    badgeAssetPath: null,
    carImagePath: null,
    carImageAlt: "Sauber Formula 1 team media placeholder",
    fallbackImagePath: sharedTeamFallback,
  },
  alfa: {
    id: "alfa",
    label: "Alfa Romeo",
    shortLabel: "ALF",
    primary: "#8b0000",
    secondary: "#f0f0f0",
    accent: "#ffffff",
    badgeAssetPath: null,
    carImagePath: null,
    carImageAlt: "Alfa Romeo Formula 1 team media placeholder",
    fallbackImagePath: sharedTeamFallback,
  },
};

const circuitAssetMap: Record<string, CircuitAsset> = {
  bahrain: {
    id: "bahrain",
    countryCode: "BH",
    region: "Sakhir",
    layoutAssetPath: "/assets/circuits/bahrain.svg",
    layoutSourceLabel: "Wikimedia Commons",
    layoutSourceUrl:
      "https://commons.wikimedia.org/wiki/File:Bahrain_International_Circuit--Grand_Prix_Layout_with_DRS.svg",
    geoJsonFeatureId: "bh-2002",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  jeddah: {
    id: "jeddah",
    countryCode: "SA",
    region: "Jeddah",
    layoutAssetPath: "/assets/circuits/jeddah.svg",
    layoutSourceLabel: "Wikimedia Commons",
    layoutSourceUrl: "https://commons.wikimedia.org/wiki/File:Jeddah_Street_Circuit_2021.svg",
    geoJsonFeatureId: "sa-2021",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  albert_park: {
    id: "albert_park",
    countryCode: "AU",
    region: "Melbourne",
    layoutAssetPath: "/assets/circuits/albert_park.svg",
    layoutSourceLabel: "Wikimedia Commons",
    layoutSourceUrl: "https://commons.wikimedia.org/wiki/File:Albert_Park_Circuit_2021.svg",
    geoJsonFeatureId: "au-1953",
    lapRecordTime: "1:19.813",
    lapRecordDriver: "Charles Leclerc",
    lapRecordYear: 2024,
  },
  monaco: {
    id: "monaco",
    countryCode: "MC",
    region: "Monte Carlo",
    layoutAssetPath: "/assets/circuits/monaco.svg",
    layoutSourceLabel: "Wikimedia Commons",
    layoutSourceUrl: "https://commons.wikimedia.org/wiki/File:Circuit_Monaco.svg",
    geoJsonFeatureId: "mc-1929",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  silverstone: {
    id: "silverstone",
    countryCode: "GB",
    region: "Silverstone",
    layoutAssetPath: "/assets/circuits/silverstone.svg",
    layoutSourceLabel: "Wikimedia Commons",
    layoutSourceUrl: "https://commons.wikimedia.org/wiki/File:Circuit_Silverstone_2011.svg",
    geoJsonFeatureId: "gb-1948",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  shanghai: {
    id: "shanghai",
    countryCode: "CN",
    region: "Shanghai",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "cn-2004",
    lapRecordTime: "1:32.238",
    lapRecordDriver: "Michael Schumacher",
    lapRecordYear: 2004,
  },
  miami: {
    id: "miami",
    countryCode: "US",
    region: "Miami",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: null,
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  suzuka: {
    id: "suzuka",
    countryCode: "JP",
    region: "Suzuka",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "jp-1962",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  monza: {
    id: "monza",
    countryCode: "IT",
    region: "Monza",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "it-1922",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  marina_bay: {
    id: "marina_bay",
    countryCode: "SG",
    region: "Singapore",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "sg-2008",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  villeneuve: {
    id: "villeneuve",
    countryCode: "CA",
    region: "Montreal",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "ca-1978",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  zandvoort: {
    id: "zandvoort",
    countryCode: "NL",
    region: "Zandvoort",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "nl-1948",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  catalunya: {
    id: "catalunya",
    countryCode: "ES",
    region: "Barcelona",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "es-1991",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  hungaroring: {
    id: "hungaroring",
    countryCode: "HU",
    region: "Budapest",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "hu-1986",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  spa: {
    id: "spa",
    countryCode: "BE",
    region: "Spa",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "be-1925",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  baku: {
    id: "baku",
    countryCode: "AZ",
    region: "Baku",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "az-2016",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  yas_marina: {
    id: "yas_marina",
    countryCode: "AE",
    region: "Yas Marina",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "ae-2009",
    lapRecordTime: "1:26.103",
    lapRecordDriver: "Max Verstappen",
    lapRecordYear: 2021,
  },
  losail: {
    id: "losail",
    countryCode: "QA",
    region: "Lusail",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "qa-2004",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  vegas: {
    id: "vegas",
    countryCode: "US",
    region: "Las Vegas",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "us-2023",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  red_bull_ring: {
    id: "red_bull_ring",
    countryCode: "AT",
    region: "Spielberg",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "at-1969",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  imola: {
    id: "imola",
    countryCode: "IT",
    region: "Imola",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "it-1953",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  interlagos: {
    id: "interlagos",
    countryCode: "BR",
    region: "Sao Paulo",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "br-1940",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  americas: {
    id: "americas",
    countryCode: "US",
    region: "Austin",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "us-2012",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
  rodriguez: {
    id: "rodriguez",
    countryCode: "MX",
    region: "Mexico City",
    layoutAssetPath: null,
    layoutSourceLabel: null,
    layoutSourceUrl: null,
    geoJsonFeatureId: "mx-1962",
    lapRecordTime: null,
    lapRecordDriver: null,
    lapRecordYear: null,
  },
};

export function getTeamAsset(teamId: string | null | undefined): TeamAsset {
  if (!teamId) {
    return fallbackTeam;
  }

  const normalizedTeamId = teamAliases[teamId] ?? teamId;

  return teamAssetMap[normalizedTeamId] ?? {
    ...fallbackTeam,
    id: normalizedTeamId,
    label: normalizedTeamId.replaceAll("_", " "),
  };
}

export function getCircuitAsset(circuitId: string | null | undefined): CircuitAsset {
  if (!circuitId) {
    return fallbackCircuit;
  }

  return circuitAssetMap[circuitId] ?? {
    ...fallbackCircuit,
    id: circuitId,
    region: circuitId.replaceAll("_", " "),
  };
}
