import { formatSeasonRaceLabel, getSeasonState } from "@/lib/server/season-state";
import { DataFreshnessBar, type DataFreshnessInfo } from "@/components/ui/data-freshness-bar";
import { formatDateLabel, formatDateTimeLabel } from "@/lib/ui/format-date";

const DAY_MS = 24 * 60 * 60 * 1000;
const STALE_AFTER_DAYS = 12;

function formatTimestamp(value: string | null | undefined) {
  if (!value) return null;
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return null;
  return formatDateLabel(parsed);
}

function describeAge(value: string | null | undefined) {
  if (!value) return { label: null, days: null as number | null };
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return { label: null, days: null };
  const days = Math.floor((Date.now() - parsed.getTime()) / DAY_MS);
  if (days < 0) return { label: null, days: 0 };
  if (days === 0) return { label: "today", days };
  if (days === 1) return { label: "1 day ago", days };
  return { label: `${days} days ago`, days };
}

/**
 * Site-wide freshness bar. The product is generated by an offline pipeline, so
 * "how current is this?" is the first question every page raises - and the
 * different surfaces legitimately sit on different snapshots. Stating the
 * results cut-off, the active race week, and the pipeline run once at the top
 * of every page removes the guesswork.
 */
export async function DataFreshnessBanner() {
  const state = await getSeasonState();
  if (!state) {
    return null;
  }

  const resultsRace = state.latest_completed_race_with_results ?? state.latest_completed_race;
  const resultsThrough = formatSeasonRaceLabel(resultsRace);
  if (resultsThrough === "Unavailable") {
    return null;
  }

  const generatedLabel = formatTimestamp(state.generated_at);
  const { label: ageLabel, days } = describeAge(state.generated_at);
  const missingFlags = state.missing_data_flags?.length ?? 0;
  const isStale = days !== null && days > STALE_AFTER_DAYS;

  const note = isStale
    ? "Snapshot is older than a race weekend; some surfaces may lag."
    : missingFlags > 0
      ? `${missingFlags} data gap${missingFlags === 1 ? "" : "s"} flagged in this snapshot.`
      : null;

  const info: DataFreshnessInfo = {
    version: state.build_version || state.generated_at || resultsThrough,
    tone: isStale || missingFlags > 0 ? "warning" : "ok",
    resultsThrough,
    nextRace: state.next_race?.race_name ? formatSeasonRaceLabel(state.next_race) : null,
    generatedLabel,
    ageLabel,
    note,
  };

  return <DataFreshnessBar info={info} />;
}
