/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ChampionshipRouteImport } from './routes/championship'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RaceweekRouteImport } from './routes/raceweek'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VsRouteImport } from './routes/vs'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AnalysisSlugRouteImport } from './routes/analysis.$slug'
import { Route as MethodDashboardRouteImport } from './routes/method_.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipRoute = ChampionshipRouteImport.update({
  id: '/championship',
  path: '/championship',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceweekRoute = RaceweekRouteImport.update({
  id: '/raceweek',
  path: '/raceweek',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VsRoute = VsRouteImport.update({
  id: '/vs',
  path: '/vs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisSlugRoute = AnalysisSlugRouteImport.update({
  id: '/analysis/$slug',
  path: '/analysis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodDashboardRoute = MethodDashboardRouteImport.update({
  id: '/method_/dashboard',
  path: '/method/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/championship': typeof ChampionshipRoute
  '/cookies': typeof CookiesRoute
  '/method': typeof MethodRoute
  '/picks': typeof PicksRoute
  '/privacy': typeof PrivacyRoute
  '/raceweek': typeof RaceweekRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vs': typeof VsRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/method/dashboard': typeof MethodDashboardRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/championship': typeof ChampionshipRoute
  '/cookies': typeof CookiesRoute
  '/method': typeof MethodRoute
  '/picks': typeof PicksRoute
  '/privacy': typeof PrivacyRoute
  '/raceweek': typeof RaceweekRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vs': typeof VsRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/method/dashboard': typeof MethodDashboardRoute
  '/analysis': typeof AnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/championship': typeof ChampionshipRoute
  '/cookies': typeof CookiesRoute
  '/method': typeof MethodRoute
  '/picks': typeof PicksRoute
  '/privacy': typeof PrivacyRoute
  '/raceweek': typeof RaceweekRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vs': typeof VsRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/method_/dashboard': typeof MethodDashboardRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/championship'
    | '/cookies'
    | '/method'
    | '/picks'
    | '/privacy'
    | '/raceweek'
    | '/sitemap.xml'
    | '/terms'
    | '/vs'
    | '/analysis/$slug'
    | '/method/dashboard'
    | '/analysis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/championship'
    | '/cookies'
    | '/method'
    | '/picks'
    | '/privacy'
    | '/raceweek'
    | '/sitemap.xml'
    | '/terms'
    | '/vs'
    | '/analysis/$slug'
    | '/method/dashboard'
    | '/analysis'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/championship'
    | '/cookies'
    | '/method'
    | '/picks'
    | '/privacy'
    | '/raceweek'
    | '/sitemap.xml'
    | '/terms'
    | '/vs'
    | '/analysis/$slug'
    | '/method_/dashboard'
    | '/analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ChampionshipRoute: typeof ChampionshipRoute
  CookiesRoute: typeof CookiesRoute
  MethodRoute: typeof MethodRoute
  PicksRoute: typeof PicksRoute
  PrivacyRoute: typeof PrivacyRoute
  RaceweekRoute: typeof RaceweekRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VsRoute: typeof VsRoute
  AnalysisSlugRoute: typeof AnalysisSlugRoute
  MethodDashboardRoute: typeof MethodDashboardRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/championship': {
      id: '/championship'
      path: '/championship'
      fullPath: '/championship'
      preLoaderRoute: typeof ChampionshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raceweek': {
      id: '/raceweek'
      path: '/raceweek'
      fullPath: '/raceweek'
      preLoaderRoute: typeof RaceweekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs': {
      id: '/vs'
      path: '/vs'
      fullPath: '/vs'
      preLoaderRoute: typeof VsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$slug': {
      id: '/analysis/$slug'
      path: '/analysis/$slug'
      fullPath: '/analysis/$slug'
      preLoaderRoute: typeof AnalysisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method_/dashboard': {
      id: '/method_/dashboard'
      path: '/method/dashboard'
      fullPath: '/method/dashboard'
      preLoaderRoute: typeof MethodDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ChampionshipRoute: ChampionshipRoute,
  CookiesRoute: CookiesRoute,
  MethodRoute: MethodRoute,
  PicksRoute: PicksRoute,
  PrivacyRoute: PrivacyRoute,
  RaceweekRoute: RaceweekRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VsRoute: VsRoute,
  AnalysisSlugRoute: AnalysisSlugRoute,
  MethodDashboardRoute: MethodDashboardRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
