/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChampionshipRouteImport } from './routes/championship'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PicksRouteImport } from './routes/picks'
import { Route as RaceweekRouteImport } from './routes/raceweek'
import { Route as VsRouteImport } from './routes/vs'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AnalysisSlugRouteImport } from './routes/analysis.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionshipRoute = ChampionshipRouteImport.update({
  id: '/championship',
  path: '/championship',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PicksRoute = PicksRouteImport.update({
  id: '/picks',
  path: '/picks',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceweekRoute = RaceweekRouteImport.update({
  id: '/raceweek',
  path: '/raceweek',
  getParentRoute: () => rootRouteImport,
} as any)
const VsRoute = VsRouteImport.update({
  id: '/vs',
  path: '/vs',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisSlugRoute = AnalysisSlugRouteImport.update({
  id: '/analysis/$slug',
  path: '/analysis/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/championship': typeof ChampionshipRoute
  '/method': typeof MethodRoute
  '/picks': typeof PicksRoute
  '/raceweek': typeof RaceweekRoute
  '/vs': typeof VsRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/championship': typeof ChampionshipRoute
  '/method': typeof MethodRoute
  '/picks': typeof PicksRoute
  '/raceweek': typeof RaceweekRoute
  '/vs': typeof VsRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/analysis': typeof AnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/championship': typeof ChampionshipRoute
  '/method': typeof MethodRoute
  '/picks': typeof PicksRoute
  '/raceweek': typeof RaceweekRoute
  '/vs': typeof VsRoute
  '/analysis/$slug': typeof AnalysisSlugRoute
  '/analysis/': typeof AnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/championship'
    | '/method'
    | '/picks'
    | '/raceweek'
    | '/vs'
    | '/analysis/$slug'
    | '/analysis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/championship'
    | '/method'
    | '/picks'
    | '/raceweek'
    | '/vs'
    | '/analysis/$slug'
    | '/analysis'
  id:
    | '__root__'
    | '/'
    | '/championship'
    | '/method'
    | '/picks'
    | '/raceweek'
    | '/vs'
    | '/analysis/$slug'
    | '/analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionshipRoute: typeof ChampionshipRoute
  MethodRoute: typeof MethodRoute
  PicksRoute: typeof PicksRoute
  RaceweekRoute: typeof RaceweekRoute
  VsRoute: typeof VsRoute
  AnalysisSlugRoute: typeof AnalysisSlugRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/championship': {
      id: '/championship'
      path: '/championship'
      fullPath: '/championship'
      preLoaderRoute: typeof ChampionshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picks': {
      id: '/picks'
      path: '/picks'
      fullPath: '/picks'
      preLoaderRoute: typeof PicksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raceweek': {
      id: '/raceweek'
      path: '/raceweek'
      fullPath: '/raceweek'
      preLoaderRoute: typeof RaceweekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs': {
      id: '/vs'
      path: '/vs'
      fullPath: '/vs'
      preLoaderRoute: typeof VsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$slug': {
      id: '/analysis/$slug'
      path: '/analysis/$slug'
      fullPath: '/analysis/$slug'
      preLoaderRoute: typeof AnalysisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionshipRoute: ChampionshipRoute,
  MethodRoute: MethodRoute,
  PicksRoute: PicksRoute,
  RaceweekRoute: RaceweekRoute,
  VsRoute: VsRoute,
  AnalysisSlugRoute: AnalysisSlugRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
